Installation of Numpy Using PIP

In [16]:

import numpy as np

In [17]:
import numpy as np

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("Matrix Multiplication:")
print(result)

Matrix Multiplication:
[[19 22]
 [43 50]]


Examples of the operations
Linear Algebra functions


In [8]:
import numpy as np

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("Matrix Multiplication:")
print(result)

# Matrix inversion
A_inv = np.linalg.inv(A)
print("\nMatrix Inversion:")
print(A_inv)

# Eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)


Matrix Multiplication:
[[19 22]
 [43 50]]

Matrix Inversion:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
# Generate random data
data = np.random.randint(0, 100, size=(5, 5))
print("Random Data:")
print(data)


Random Data:
[[53 68 79 11 38]
 [80 21 85 13 11]
 [59 53 76 42 83]
 [32 28 80 48 44]
 [18 37  8 36 14]]


Statistical Functions

In [10]:
import numpy as np

# Generate random data
data = np.random.randint(0, 100, size=(5, 5))
print("Random Data:")
print(data)

# Mean
mean = np.mean(data)
print("\nMean:")
print(mean)

# Standard deviation
std_dev = np.std(data)
print("\nStandard Deviation:")
print(std_dev)

# Correlation coefficient
corr_coef = np.corrcoef(data)
print("\nCorrelation Coefficient:")
print(corr_coef)


Random Data:
[[29 27 14 27 38]
 [12 92  1 91 61]
 [40 53  5 48 59]
 [30 61 73 20 14]
 [47  2  5 43 48]]

Mean:
37.6

Standard Deviation:
25.58280672639341

Correlation Coefficient:
[[ 1.          0.46233805  0.90923422 -0.82416465  0.69479463]
 [ 0.46233805  1.          0.76171082 -0.32588647  0.03505443]
 [ 0.90923422  0.76171082  1.         -0.69247967  0.48309368]
 [-0.82416465 -0.32588647 -0.69247967  1.         -0.95115406]
 [ 0.69479463  0.03505443  0.48309368 -0.95115406  1.        ]]


In [ ]:
arr= np.array([1,2,3],dtype=np.float64)

ARRAYS: Key Features of NumPy Arrays

In [ ]:
import numpy as np

# Creating a 1-dimensional NumPy array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print("Shape:", arr1d.shape)  # Shape of the array
print("Data Type:", arr1d.dtype)  # Data type of the elements
print()

# Creating a 2-dimensional NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2d)
print("Shape:", arr2d.shape)
print()

# Basic operations with NumPy arrays
print("Basic Operations:")
print("Array Addition:")
result_addition = arr1d + 10  # Adding scalar 10 to each element
print(result_addition)
print()

print("Array Multiplication:")
result_multiplication = arr1d * 2  # Multiplying each element by scalar 2
print(result_multiplication)
print()

print("Element-wise Exponential:")
result_exponential = np.exp(arr1d)  # Exponential function applied to each element
print(result_exponential)
print()

print("Matrix Multiplication:")
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix_multiplication = np.dot(matrix1, matrix2)  # Matrix multiplication
print(result_matrix_multiplication)


1D Array:
[1 2 3 4 5]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

Basic Operations:
Array Addition:
[11 12 13 14 15]

Array Multiplication:
[ 2  4  6  8 10]

Element-wise Exponential:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Matrix Multiplication:
[[19 22]
 [43 50]]


•	Homogeneous Data Type

In [ ]:
import numpy as np

# Creating a NumPy array with integers
arr_int = np.array([1, 2, 3, 4, 5])

# Creating a NumPy array with floating-point numbers
arr_float = np.array([1.0, 2.5, 3.7, 4.2, 5.9])

# Creating a NumPy array with strings
arr_str = np.array(['apple', 'banana', 'orange'])

# Checking data types of arrays
print("Data Type of arr_int:", arr_int.dtype)
print("Data Type of arr_float:", arr_float.dtype)
print("Data Type of arr_str:", arr_str.dtype)


Data Type of arr_int: int64
Data Type of arr_float: float64
Data Type of arr_str: <U6


Multidimensional Arrays: Creating Multidimensional Arrays

In [ ]:
import numpy as np

# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Creating a 3D array
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])


Accessing Elements in Multidimensional Arrays

In [ ]:
# Accessing elements in a 2D array
print(matrix[0, 0])  # Accessing element at row 0, column 0
print(matrix[1, 2])  # Accessing element at row 1, column 2

# Accessing elements in a 3D array
print(array_3d[0, 1, 2])  # Accessing element at first matrix, second row, third column
print(array_3d[1, 0, 1])  # Accessing element at second matrix, first row, second column


1
6
6
8


Performing Operations on Multidimensional Arrays

In [ ]:
# Sum along rows and columns of a 2D array
row_sum = np.sum(matrix, axis=1)  # Sum along rows
col_sum = np.sum(matrix, axis=0)  # Sum along columns

print("Row Sum:", row_sum)
print("Column Sum:", col_sum)

# Element-wise multiplication of two 2D arrays
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

result = array1 * array2
print("Element-wise Multiplication Result:")
print(result)


Row Sum: [ 6 15 24]
Column Sum: [12 15 18]
Element-wise Multiplication Result:
[[ 5 12]
 [21 32]]


Broadcasting

In [ ]:
import numpy as np

# Define a 1-dimensional array
arr1 = np.array([1, 2, 3])
scalar = 10

# Add scalar value to the array using broadcasting
result = arr1 + scalar

print(result)  # Output: [11 12 13]


[11 12 13]


In [ ]:
import numpy as np

# Creating a 1D array
array1 = np.array([1, 2, 3])

# Creating a scalar value
scalar = 2

# Performing element-wise addition between array and scalar
result = array1 + scalar

print("Array + Scalar:")
print(result)


Array + Scalar:
[3 4 5]


Creating NumPy Arrays

In [ ]:
import numpy as np

# Creating a NumPy array from a Python list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print("NumPy Array from Python List:")
print(my_array)

# Creating a NumPy array from a Python tuple
my_tuple = (6, 7, 8, 9, 10)
my_array_from_tuple = np.array(my_tuple)

print("\nNumPy Array from Python Tuple:")
print(my_array_from_tuple)


NumPy Array from Python List:
[1 2 3 4 5]

NumPy Array from Python Tuple:
[ 6  7  8  9 10]


Special Arrays

In [ ]:
import numpy as np

# Creating an array of zeros
zeros_array = np.zeros((3, 4))  # Create a 3x4 array filled with zeros
print("Array of Zeros:")
print(zeros_array)

# Creating an array of ones
ones_array = np.ones((2, 3))  # Create a 2x3 array filled with ones
print("\nArray of Ones:")
print(ones_array)

# Creating an array with a specific fill value
full_array = np.full((2, 2), 7)  # Create a 2x2 array filled with the value 7
print("\nArray with Specific Fill Value:")
print(full_array)

# Creating an empty array (uninitialized, content may vary)
empty_array = np.empty((2, 2))  # Create a 2x2 empty array
print("\nEmpty Array:")
print(empty_array)

# Creating a sequence of numbers
sequence_array = np.arange(0, 10, 2)  # Create an array with values from 0 to 10 (exclusive) with a step of 2
print("\nSequence Array:")
print(sequence_array)

# Creating a sequence of numbers with a specified number of elements
linspace_array = np.linspace(0, 1, 5)  # Create an array with 5 evenly spaced values from 0 to 1
print("\nLinspace Array:")
print(linspace_array)


Array of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Array with Specific Fill Value:
[[7 7]
 [7 7]]

Empty Array:
[[2.47e-323 5.93e-323]
 [1.04e-322 1.58e-322]]

Sequence Array:
[0 2 4 6 8]

Linspace Array:
[0.   0.25 0.5  0.75 1.  ]


•	Arange and Linspace

In [ ]:
import numpy as np

# Using np.arange() to create an array with values from 0 to 9 (exclusive) with a step size of 2
arr_arange = np.arange(0, 10, 2)
print("Array created using np.arange():")
print(arr_arange)


Array created using np.arange():
[0 2 4 6 8]


In [ ]:
import numpy as np

# Using np.linspace() to create an array with 5 evenly spaced values from 0 to 1
arr_linspace = np.linspace(0, 1, 5)
print("Array created using np.linspace():")
print(arr_linspace)


Array created using np.linspace():
[0.   0.25 0.5  0.75 1.  ]


# NUMPY ARRAY MANIPULATION

In [ ]:
import numpy as np

# Creating a NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the array to a 2x3 matrix
reshaped_array = original_array.reshape(2, 3)

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


flattenned array

In [ ]:
import numpy as np

# Creating a 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# Flattening the array
flattened_array = original_array.flatten()

print("Original Array:")
print(original_array)

print("\nFlattened Array:")
print(flattened_array)


Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]


concatenating arrays

In [ ]:
import numpy as np

# Creating two arrays to concatenate
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Concatenating arrays along axis 0 (rows)
concatenated_array_axis0 = np.concatenate((array1, array2), axis=0)

# Concatenating arrays along axis 1 (columns)
concatenated_array_axis1 = np.concatenate((array1, array2), axis=1)

print("Concatenated Array along axis 0 (rows):")
print(concatenated_array_axis0)

print("\nConcatenated Array along axis 1 (columns):")
print(concatenated_array_axis1)


Concatenated Array along axis 0 (rows):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated Array along axis 1 (columns):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


stacking arrays

In [ ]:
import numpy as np

# Creating two arrays to stack
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

# Vertically stacking arrays
stacked_vertically = np.vstack((array1, array2))

# Horizontally stacking arrays
stacked_horizontally = np.hstack((array1, array2))

print("Vertically Stacked Array:")
print(stacked_vertically)

print("\nHorizontally Stacked Array:")
print(stacked_horizontally)


Vertically Stacked Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked Array:
[[1 2 5 6]
 [3 4 7 8]]


# MATRIX IN NUMPY

In [ ]:
import numpy as np

# Creating a 2x3 matrix using np.array()
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Matrix:")
print(matrix)


Matrix:
[[1 2 3]
 [4 5 6]]


types of matrices

In [ ]:
import numpy as np

# Creating a 3x3 matrix filled with zeros
zeros_matrix = np.zeros((3, 3))
print("Zeros Matrix:")
print(zeros_matrix)

# Creating a 2x2 matrix filled with ones
ones_matrix = np.ones((2, 2))
print("\nOnes Matrix:")
print(ones_matrix)

# Creating a 4x4 identity matrix
identity_matrix = np.eye(4)
print("\nIdentity Matrix:")
print(identity_matrix)

# Creating a 3x2 matrix with random values
random_matrix = np.random.rand(3, 2)
print("\nRandom Matrix:")
print(random_matrix)


Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix:
[[1. 1.]
 [1. 1.]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Matrix:
[[0.69882668 0.06364985]
 [0.55687113 0.06546818]
 [0.8881213  0.7205363 ]]


matrix attributes
shape

In [ ]:
import numpy as np

# Creating a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Getting the shape of the matrix
matrix_shape = matrix.shape

print("Matrix Shape:", matrix_shape)


Matrix Shape: (2, 3)


transpose

In [ ]:
import numpy as np

# Creating a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Getting the transpose of the matrix
matrix_transpose = matrix.T

print("Original Matrix:")
print(matrix)

print("\nTranspose of the Matrix:")
print(matrix_transpose)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Transpose of the Matrix:
[[1 4]
 [2 5]
 [3 6]]


matrix multiplication

In [ ]:
import numpy as np

# Creating two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Performing matrix multiplication using np.dot()
result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Multiplication:")
print(result_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


matrix multiplication with np.dot()

In [ ]:
import numpy as np

# Creating two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Performing matrix multiplication using np.dot()
result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Multiplication:")
print(result_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


# OPERATIONS ON NUMPY ARRAYS

In [ ]:
import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Addition
addition_result = np.add(array1, array2)

# Subtraction
subtraction_result = np.subtract(array1, array2)

# Multiplication
multiplication_result = np.multiply(array1, array2)

# Division
division_result = np.divide(array1, array2)

# Exponentiation
exponentiation_result = np.power(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)
print("Exponentiation Result:", exponentiation_result)


Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Addition Result: [ 6  8 10 12]
Subtraction Result: [-4 -4 -4 -4]
Multiplication Result: [ 5 12 21 32]
Division Result: [0.2        0.33333333 0.42857143 0.5       ]
Exponentiation Result: [    1    64  2187 65536]


basic element wise operations

In [ ]:
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Adding a scalar value to each element
addition_result = array + 10

# Subtracting a scalar value from each element
subtraction_result = array - 2

# Multiplying each element by a scalar value
multiplication_result = array * 3

# Dividing each element by a scalar value
division_result = array / 2

# Computing the square of each element
square_result = array ** 2

print("Original Array:", array)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)
print("Square Result:", square_result)


Original Array: [1 2 3 4 5]
Addition Result: [11 12 13 14 15]
Subtraction Result: [-1  0  1  2  3]
Multiplication Result: [ 3  6  9 12 15]
Division Result: [0.5 1.  1.5 2.  2.5]
Square Result: [ 1  4  9 16 25]


element wise functions in numpy

In [ ]:
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Square root of each element
sqrt_result = np.sqrt(array)

# Exponential function applied to each element
exp_result = np.exp(array)

# Trigonometric sine function applied to each element
sin_result = np.sin(array)

# Natural logarithm applied to each element
log_result = np.log(array)

print("Original Array:", array)
print("Square Root Result:", sqrt_result)
print("Exponential Result:", exp_result)
print("Sine Result:", sin_result)
print("Logarithm Result:", log_result)


Original Array: [1 2 3 4 5]
Square Root Result: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm Result: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


broadcasting in numpy

In [ ]:
import numpy as np

# Creating arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
scalar = 10

# Performing addition with broadcasting
result = array1 + scalar

print("Array 1:")
print(array1)

print("\nScalar Value:", scalar)

print("\nResult of Broadcasting:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Scalar Value: 10

Result of Broadcasting:
[[11 12 13]
 [14 15 16]]


broadcasting with different dimensions

In [ ]:
import numpy as np

# Creating arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([10, 20, 30])

# Performing addition with broadcasting
result = array1 + array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nResult of Broadcasting:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[10 20 30]

Result of Broadcasting:
[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

# Creating a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Accessing individual elements using basic indexing
print("First Element:", array[0])
print("Last Element:", array[-1])

# Slicing to access a subset of elements
print("Sliced Array:", array[1:4])  # Elements from index 1 to 3 (exclusive)

# Modifying array elements using indexing
array[2] = 10
print("Modified Array:", array)


First Element: 1
Last Element: 5
Sliced Array: [2 3 4]
Modified Array: [ 1  2 10  4  5]


In [ ]:
import numpy as np

# Creating a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Generating a boolean mask based on a condition
mask = array > 3

# Using the boolean mask to select elements from the array
selected_elements = array[mask]

print("Original Array:", array)
print("Boolean Mask:", mask)
print("Selected Elements:", selected_elements)


Original Array: [1 2 3 4 5]
Boolean Mask: [False False False  True  True]
Selected Elements: [4 5]


In [ ]:
import numpy as np

# Creating a 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Slicing along rows and columns
row_slice = array[0:2, :]  # Selecting rows 0 and 1, and all columns
col_slice = array[:, 1:3]   # Selecting all rows, and columns 1 and 2

print("Original Array:")
print(array)

print("\nRow Slice:")
print(row_slice)

print("\nColumn Slice:")
print(col_slice)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row Slice:
[[1 2 3]
 [4 5 6]]

Column Slice:
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
import numpy as np

# Creating a 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Slicing along different axes
row_slice = array[0:2, :]    # Slicing along rows
col_slice = array[:, 1:3]    # Slicing along columns
element_slice = array[1, 1]  # Slicing a single element
subarray_slice = array[1:, :2]  # Slicing a subarray

print("Original Array:")
print(array)

print("\nRow Slice:")
print(row_slice)

print("\nColumn Slice:")
print(col_slice)

print("\nSingle Element Slice:")
print(element_slice)

print("\nSubarray Slice:")
print(subarray_slice)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row Slice:
[[1 2 3]
 [4 5 6]]

Column Slice:
[[2 3]
 [5 6]
 [8 9]]

Single Element Slice:
5

Subarray Slice:
[[4 5]
 [7 8]]


In [ ]:
import numpy as np

# Generate a single random number between 0 and 1
random_number = np.random.rand()
print("Random Number:", random_number)

# Generate an array of random numbers with shape (3, 4)
random_array = np.random.rand(3, 4)
print("Random Array:")
print(random_array)


Random Number: 0.9129045191041149
Random Array:
[[0.15910359 0.33658377 0.30680771 0.87054274]
 [0.17335922 0.97762645 0.51097019 0.57232321]
 [0.50974844 0.19542195 0.7992713  0.64395945]]


In [ ]:
import numpy as np

# Generate random numbers from standard normal distribution (mean=0, std=1)
normal_distribution = np.random.randn(1000)

# Generate random numbers from uniform distribution between 0 and 1
uniform_distribution = np.random.rand(1000)

# Generate random integers between 1 and 10
random_integers = np.random.randint(1, 11, size=1000)

# Generate random numbers from exponential distribution with scale=1
exponential_distribution = np.random.exponential(scale=1, size=1000)

# Generate random numbers from Poisson distribution with lambda=5
poisson_distribution = np.random.poisson(lam=5, size=1000)

# Generate random numbers from binomial distribution with n=10 and p=0.5
binomial_distribution = np.random.binomial(n=10, p=0.5, size=1000)

# Generate random numbers from logistic distribution with mean=0 and scale=1
logistic_distribution = np.random.logistic(loc=0, scale=1, size=1000)

# Generate random numbers from gamma distribution with shape=2 and scale=2
gamma_distribution = np.random.gamma(shape=2, scale=2, size=1000)

# Generate random numbers from geometric distribution with p=0.3
geometric_distribution = np.random.geometric(p=0.3, size=1000)

# Generate random numbers from triangular distribution with parameters a=0, b=2, and c=1
triangular_distribution = np.random.triangular(left=0, mode=1, right=2, size=1000)

# Generate random numbers from Weibull distribution with shape=1.5
weibull_distribution = np.random.weibull(a=1.5, size=1000)

# Generate random numbers from beta distribution with alpha=2 and beta=5
beta_distribution = np.random.beta(a=2, b=5, size=1000)


In [ ]:
import numpy as np

# Create a NumPy array
array = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Sort the array in-place
array.sort()

print("Sorted Array:", array)


Sorted Array: [1 1 2 3 4 5 6 9]


In [ ]:
import numpy as np

# Create a NumPy array
array = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Get the sorted indices
sorted_indices = np.argsort(array)

# Sort the array based on the sorted indices
sorted_array = array[sorted_indices]

print("Original Array:", array)
print("Sorted Indices:", sorted_indices)
print("Sorted Array:", sorted_array)


Original Array: [3 1 4 1 5 9 2 6]
Sorted Indices: [1 3 6 0 2 4 7 5]
Sorted Array: [1 1 2 3 4 5 6 9]


In [ ]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Find indices where elements are greater than 3
indices = np.where(array > 3)

print("Original Array:", array)
print("Indices where elements are greater than 3:", indices)


Original Array: [1 2 3 4 5]
Indices where elements are greater than 3: (array([3, 4]),)


In [ ]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Check condition for each element
condition_result = array > 3

print("Original Array:", array)
print("Condition Result:", condition_result)


Original Array: [1 2 3 4 5]
Condition Result: [False False False  True  True]


In [ ]:
from PIL import Image
import numpy as np

# Specify the full path to the image file
image_path = '/path/to/example_image.jpg'

# Read the image file using Pillow
image = Image.open(image_path)

# Convert the image to a NumPy array
image_array = np.array(image)

# Display the shape and data type of the image array
print("Image Shape:", image_array.shape)
print("Image Data Type:", image_array.dtype)


FileNotFoundError: [Errno 2] No such file or directory: '/path/to/example_image.jpg'

In [ ]:
from PIL import Image
import numpy as np

# Read the image file using Pillow
image = Image.open('example_image.jpg')

# Convert the image to a NumPy array
image_array = np.array(image)

# Adjust brightness by adding a constant value to all pixel values
brightness_factor = 50
brightened_image_array = np.clip(image_array + brightness_factor, 0, 255).astype(np.uint8)

# Convert the modified NumPy array back to an image
brightened_image = Image.fromarray(brightened_image_array)

# Display the original and brightened images
image.show()
brightened_image.show()


FileNotFoundError: [Errno 2] No such file or directory: 'example_image.jpg'

In [ ]:
from PIL import Image
import numpy as np

# Read the image file using Pillow
image = Image.open('example_image.jpg')

# Convert the image to a NumPy array
image_array = np.array(image)

# Resize the image array using NumPy's array manipulation functions
new_height = 300
new_width = 400
resized_image_array = np.array(Image.fromarray(image_array).resize((new_width, new_height)))

# Convert the resized NumPy array back to an image
resized_image = Image.fromarray(resized_image_array)

# Display the original and resized images
image.show()
resized_image.show()


FileNotFoundError: [Errno 2] No such file or directory: 'example_image.jpg'

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Convert the NumPy array to a Pandas DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

# Display the DataFrame
print("Pandas DataFrame:")
print(df)

# Perform data manipulation with Pandas
df['D'] = df['A'] + df['B']  # Adding a new column 'D' as the sum of columns 'A' and 'B'

# Display the modified DataFrame
print("\nModified Pandas DataFrame:")
print(df)


Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Modified Pandas DataFrame:
   A  B  C   D
0  1  2  3   3
1  4  5  6   9
2  7  8  9  15


In [1]:
!git config --global user.name "nemwelamoro"
!git config --global user.email "nemwelamoro@gmail.com"


In [3]:
!git clone https://github.com/nemwelamoro/Numpy-operations.git

Cloning into 'Numpy-operations'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.


In [13]:

%cd Numpy-operations/


/content/Numpy-operations


In [18]:
!git add .


In [19]:
!git commit -m "Initial project commit"


On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [21]:
!git push origin main


fatal: could not read Username for 'https://github.com': No such device or address
